pipeline {
 agent any
 tools{
 maven 'maven 3.6.1'
 }
 stages{
 stage("building"){
 steps{
 echo 'Compiling worker app'
 dir('worker'){
 sh 'mvn compile'
 }
 }
 }
 stage("testing"){
 steps{
 echo 'Running Unit Tets on worker app'
 }
 }
 stage("package"){
 steps{
 echo 'Packaging worker app'
 }
 }
 }
 post{
 always{
 echo 'Building multibranch pipeline for worker project is completed..'
 }
 }
}